### ISSUE TITLE
Issue with predicates?

### ISSUE THREAD

**Issue by mlliarm** [mlliarm/ia#14]
Hello @pmoura !

I started writing some examples but it seems that something is broken. Can you help?

I'll assign this to you if that's okay.

Here's what I did:

```logtalk
?- A = new(1,2).
A = new(1, 2).

?- mid(A, Mid).
ERROR: Unknown procedure: mid/2 (DWIM could not correct goal)
?- midpoint(A, Mid).
ERROR: Unknown procedure: midpoint/2 (DWIM could not correct goal)
?- A = [1,2].
A = [1, 2].

?- midpoint(A, Mid).
ERROR: Unknown procedure: midpoint/2 (DWIM could not correct goal)

?- magnitude(A, M).
ERROR: Unknown procedure: magnitude/2 (DWIM could not correct goal)
```

I see that the predicates work only with a representation of the Interval as a list [a,b]. So they don't work with the `new` predicate, for now.

Question: will the user have access to the shorthands of the predicates, eg `mid`? 

Thanks, and apologies for not having started earlier.

**Comment by pmoura** [comment]
There's a big misunderstanding here. Assuming you have loaded the library, the predicates are available by sending messages to the `interval_arithmetic` object:

```text
?- logtalk_load(loader).
...

?- interval_arithmetic::new(1,2,Interval).
Interval = ...
```

I.e. Logtalk is **not** based on an import/export semantics that you find with Prolog modules. In the code you wrote, loading the library doesn't make the predicates available for calling without reference to the library objects as in your sample queries.

You can use implicit message sending from within an object using the [`uses/2`](https://logtalk.org/manuals/refman/directives/uses_2.html) directive.

**Comment by mlliarm** [comment]
Oh yes !!!

Thanks.flr the correction!

---
Michail L. Liarmakopoulos, MSc
