### ISSUE TITLE
Test interval_arithmetic_mul_3_01 of test set ia/ failed

### ISSUE THREAD

**Issue by pmoura** [mlliarm/ia#25]
Test object: `tests`  
Test file: ia/tests.lgt:109-112

Failure:  
&emsp;test assertion failed: `i(1*3,2*4)==i(3,8)`

Note: (none)

Time: 0.00014500000000028379 seconds

Git branch: main  
Commit hash: 93ba103  
Commit author: milia  
Commit date: 2022-01-22T09:24:42+01:00  
Commit message:  
&emsp;work damn it

**Comment by mlliarm** [comment]
Hello, @pmoura,

I'm not sure I understand where this comes from.

The `interval_arithmetic::mul/3` predicate seems to be working fine:

```logtalk
?- interval_arithmetic::mul(i(1,2), i(3,4), Mul).
Mul = i(3, 8).
``` 
Can you provide some more information?
