### ISSUE TITLE
Test interval_arithmetic_div_3_01 of test set ia/ failed

### ISSUE THREAD

**Issue by pmoura** [mlliarm/ia#26]
Test object: `tests`  
Test file: ia/tests.lgt:121-124

Failure:  
&emsp;test assertion failed: `i(1*0.20000000000000001,2*0.25)==i(0.20000000000000001,0.5)`

Note: (none)

Time: 0.00027200000000004998 seconds

Git branch: main  
Commit hash: 93ba103  
Commit author: milia  
Commit date: 2022-01-22T09:24:42+01:00  
Commit message:  
&emsp;work damn it

**Comment by mlliarm** [comment]
Hello, @pmoura,

I'm not sure I understand where this comes from.

The `interval_arithmetic::div/3` predicate seems to be working fine:

```logtalk
?- interval_arithmetic::div(i(1,2),i(4,5),Div).
Div = i(0.2, 0.5).
``` 
Can you provide some more information?

**Comment by pmoura** [comment]
The failure is due to `2*0.25 == 0.5` failing as there are not equal terms. But I cannot reproduce the test failure locally with 5f29de593580514a414c30e7e0ca2d8422e004ee.

P.S. Going to push an update to the workflow so that we get a URL link for the test file and test lines.

**Comment by mlliarm** [comment]
Okay, thanks. I'll check them again later today.

**Comment by pmoura** [comment]
Fixed.
